name: Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Latex
      run: sudo apt-get install texlive-bibtex-extra texlive-font-utils texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended texlive-plain-generic
    - name: Install Latexmk
      run: sudo apt-get install latexmk
    - name: Install netpbm
      run: sudo apt-get  install netpbm poppler-utils imagemagick
    - name: Install enchant
      run: sudo apt-get install python3-enchant
    - name: Install spinx 
      run: sudo apt-get install python-sphinx-rtd-theme python-sphinx
    - name: Sphinx and contrib
      run: sudo pip3 install matplotlib==3.4.0 sphinxcontrib-spelling sphinxcontrib-bibtex sphinxcontrib-tikz sphinxcontrib-video jinja2==3.0.3
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        submodules: 'true' 
    - name: Build and Commit
      uses: cnp3/pages@master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
